/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Textbook sidebar - manually defined for explicit ordering
  textbookSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: '📚 Introduction',
    },
    {
      type: 'category',
      label: 'Core Chapters',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'physical-ai-intro',
          label: '1. Introduction to Physical AI',
        },
        {
          type: 'doc',
          id: 'humanoid-robotics-fundamentals',
          label: '2. Humanoid Robotics Fundamentals',
        },
        {
          type: 'doc',
          id: 'sensors-perception',
          label: '3. Sensors and Perception',
        },
        {
          type: 'doc',
          id: 'actuators-motion',
          label: '4. Actuators and Motion',
        },
        {
          type: 'doc',
          id: 'ai-robot-control',
          label: '5. AI for Robot Control',
        },
        {
          type: 'doc',
          id: 'manipulation-dexterity',
          label: '6. Manipulation and Dexterity',
        },
      ],
    },
    {
      type: 'category',
      label: 'Advanced Topics (Optional)',
      collapsed: true,
      items: [
        {
          type: 'doc',
          id: 'safety-ethics',
          label: '7. Safety and Ethics',
        },
        {
          type: 'doc',
          id: 'future-trends',
          label: '8. Future Trends and Applications',
        },
      ],
    },
  ],

  // Alternative: Auto-generated sidebar from filesystem
  // Uncomment below and comment above to use auto-generation
  /*
  textbookSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Generate sidebar from docs directory
    },
  ],
  */
};

module.exports = sidebars;
